services:
  - type: web
    name: notify-me-backend
    runtime: docker
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
