/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listDevices"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devices/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["registerDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devices/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateDevice"];
    trace?: never;
  };
  "/notifications/apps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listApps"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["syncPullNotifications"];
    put?: never;
    post: operations["syncPushNotifications"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app-settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAppSettings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app-settings/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["syncAppSettings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/app-settings/upload-icon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["uploadAppIcon"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/hello": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["hello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DeviceResponse: {
      id?: string;
      deviceId?: string;
      deviceName?: string;
      brand?: string;
      model?: string;
      osName?: string;
      osVersion?: string;
      appVersion?: string;
      expoPushToken?: string;
      platform?: string;
      pushEnabled?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    RegisterDeviceRequest: {
      deviceId?: string;
      deviceName?: string;
      brand?: string;
      model?: string;
      osName?: string;
      osVersion?: string;
      appVersion?: string;
      expoPushToken?: string;
      platform?: string;
    };
    UpdateDeviceRequest: {
      pushEnabled?: boolean;
    };
    NotificationResponse: {
      id: string;
      deviceId: string;
      packageName: string;
      appName: string;
      title: string;
      text: string;
      timestamp: number;
      createdAt: string;
      updatedAt: string;
      deletedAt?: string | null;
      revision: number;
    };
    AppSummaryResponse: {
      packageName: string;
      appName: string;
      totalCount: number;
      latest: components["schemas"]["NotificationResponse"];
    };
    AppSummaryPageResponse: {
      content?: components["schemas"]["AppSummaryResponse"][];
      page?: number;
      size?: number;
      totalElements?: number;
      totalPages?: number;
    };
    SyncPushItem: {
      id: string;
      deviceId: string;
      packageName: string;
      appName: string;
      title: string;
      text: string;
      timestamp: number;
      updatedAt: number;
      deletedAt?: number | null;
    };
    SyncPushRequest: {
      items: components["schemas"]["SyncPushItem"][];
    };
    SyncPushResultItem: {
      id: string;
      accepted: boolean;
      revision: number;
    };
    SyncPushResponse: {
      results: components["schemas"]["SyncPushResultItem"][];
    };
    SyncRecord: {
      id: string;
      deviceId: string;
      packageName: string;
      appName: string;
      title: string;
      text: string;
      timestamp: number;
      updatedAt: number;
      deletedAt?: number | null;
      revision: number;
    };
    SyncPullResponse: {
      items: components["schemas"]["SyncRecord"][];
      nextSince?: number | null;
      nextBefore?: number | null;
      hasMore: boolean;
      serverRevision: number;
    };
    AppSettingItem: {
      packageName: string;
      appName: string;
      enabled: boolean;
      isSystemApp: boolean;
      appIconUrl?: string | null;
      updatedAt: number;
    };
    SyncAppSettingsRequest: {
      settings: components["schemas"]["AppSettingItem"][];
    };
    SyncAppSettingsResponse: {
      created?: number;
      updated?: number;
    };
    UploadAppIconRequest: {
      packageName: string;
      appName: string;
      iconBase64: string;
    };
    UploadAppIconResponse: {
      packageName: string;
      appIconUrl?: string | null;
    };
    RegisterDeviceResponse: {
      id?: string;
      deviceId?: string;
      deviceName?: string;
      brand?: string;
      model?: string;
      osName?: string;
      osVersion?: string;
      appVersion?: string;
      expoPushToken?: string;
      platform?: string;
      pushEnabled?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listDevices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DeviceResponse"][];
        };
      };
    };
  };
  registerDevice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDeviceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["RegisterDeviceResponse"];
        };
      };
    };
  };
  updateDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDeviceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DeviceResponse"];
        };
      };
    };
  };
  listApps: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AppSummaryPageResponse"];
        };
      };
    };
  };
  syncPullNotifications: {
    parameters: {
      query?: {
        since?: number;
        before?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SyncPullResponse"];
        };
      };
    };
  };
  syncPushNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SyncPushRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SyncPushResponse"];
        };
      };
    };
  };
  getAppSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AppSettingItem"][];
        };
      };
    };
  };
  syncAppSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SyncAppSettingsRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SyncAppSettingsResponse"];
        };
      };
    };
  };
  uploadAppIcon: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadAppIconRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UploadAppIconResponse"];
        };
      };
    };
  };
  hello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
