spring.application.name=notifyme

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Clerk Authentication
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URI}
