name: Mobile CI

on:
  push:
    branches: [main]
    paths:
      - 'mobile/**'
  workflow_dispatch:

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  continuously-deploy:
    runs-on: ubuntu-latest
    concurrency: continuous-deploy-fingerprint-main
    permissions:
      contents: read

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: mobile/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: mobile

      - name: Setup EAS
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Continuously Deploy
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          profile: production
          branch: production
          working-directory: mobile
